### ISSUE TITLE
Verify BasicAuth works when configured via API

### ISSUE THREAD

**Issue by copelco** [caktus/ansible-collection-caktus-tech-support#21]
Configure an uptime test for https://staging.caktusgroup.com/

**Comment by ronardcaktus** [comment]
What is the login and password for the site?

**Comment by copelco** [comment]
Support issue I opened:

> I'm having trouble using basic_user and basic_pass with the new API. When I create or update, the uptime test doesn't appear to save provided credentials for use.

Response from StatusCake:

> For security this is something we actively stop from being displayed in an API response. Much like the GUI. We do not reveal the user/pass that's been put in place.
>
> I can ensure you though that they are being saved as expected, and used within the confines of an uptime test only.

**Comment by ronardcaktus** [comment]
I contacted Statuscake on 1/13/22 explaining the issue - still no response from the Statuscake team on regards to a resolution.

**Comment by copelco** [comment]
As a work around, if a BasicAuth test is updated via the web UI to work, will a successive run of the API call cause it to become unset?
