### ISSUE TITLE
Convert all `_csv` arguments to expect lists rather than strings

### ISSUE THREAD

**Issue by copelco** [caktus/ansible-collection-caktus-tech-support#22]
Update statuscake module util to use these kwargs:

* `contact_groups`
* `dns_ip`
* `status_codes`
* `tags`

Before sending requests to StatusCake, the util should see if any of the above keys are in `self.config`, swap in the _csv kwarg if so, and set the value to `",".join(value)`.

AC:
* [x] `_csv` should be removed from the name.
* [x] User can define yaml lists for these attributes any they are automatically converted, e.g.:

```yaml
tags:
    - Production
    - Test
```

**Comment by ronardcaktus** [comment]
I think this is what we want, but I am not completely certain, @copelco.
![Screen Shot 2022-01-11 at 5 06 57 PM](https://user-images.githubusercontent.com/87770895/149029144-0943cb7c-90ab-4fc6-bec1-8c75a0ad6c97.png)
 See the changes I pushed on the PR.

**Comment by copelco** [comment]
Yup! Then it needs to make `self.config['tags_csv'] = 'Production,Test'`
