### ISSUE TITLE
`statuscake_monitoring` role should support all module parameters

### ISSUE THREAD

**Issue by copelco** [caktus/ansible-collection-caktus-tech-support#24]
The role currently only implements a [subset of parameters](https://github.com/caktus/ansible-collection-caktus-hosting-services/blob/309cb166839f86876eb55ec5c5438c015c7610c4/roles/statuscake_monitoring/tasks/main.yml#L10-L21). This list should be expanded to support [all available module parameters](https://github.com/caktus/ansible-collection-caktus-hosting-services/blob/309cb166839f86876eb55ec5c5438c015c7610c4/plugins/modules/statuscake_uptime_test.py#L10-L49).

**Comment by ronardcaktus** [comment]
Added remaining module parameters on the API.
